SEQ_LEN = 60                               # last 60 minutes
FUTURE_PERIOD_PREDICT = 20                  # predict movement in 3 minutes
RATIO_TO_PREDICT = "BTC-USD"
# currencies = ["BTCUSDT", "LTCUSDT", "ETHUSDT"]
currencies = ["BTCUSDT", "BCHABCUSDT", "ETHUSDT", "EOSUSDT"]
OPEN_TIME_IDX = 0
OPEN_IDX = 1
HIGH_IDX = 2
LOW_IDX = 3
CLOSE_IDX = 4
VOLUME_IDX = 5
EPOCHS = 25
BATCH_SIZE = 128
LEARNING_RATE = 0.0005
DECAY = 1e-7
LOSS = 'sparse_categorical_crossentropy'
INPUT_DIM = 12                             # n_coins * [close, vol] + 3
